// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: inventory.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UUID          string                 `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=Unit,proto3" json:"Unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Item) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UUID          string                 `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	DatetimeMs    int64                  `protobuf:"varint,4,opt,name=DatetimeMs,proto3" json:"DatetimeMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Transaction) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetDatetimeMs() int64 {
	if x != nil {
		return x.DatetimeMs
	}
	return 0
}

type TransactionLine struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ID              int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TransactionUUID string                 `protobuf:"bytes,2,opt,name=TransactionUUID,proto3" json:"TransactionUUID,omitempty"`
	AccountUUID     string                 `protobuf:"bytes,3,opt,name=AccountUUID,proto3" json:"AccountUUID,omitempty"`
	ItemUUID        string                 `protobuf:"bytes,4,opt,name=ItemUUID,proto3" json:"ItemUUID,omitempty"`
	Quantity        float64                `protobuf:"fixed64,5,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Unit            string                 `protobuf:"bytes,6,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Price           float64                `protobuf:"fixed64,7,opt,name=Price,proto3" json:"Price,omitempty"`
	Currency        string                 `protobuf:"bytes,8,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Note            string                 `protobuf:"bytes,9,opt,name=Note,proto3" json:"Note,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionLine) Reset() {
	*x = TransactionLine{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionLine) ProtoMessage() {}

func (x *TransactionLine) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionLine.ProtoReflect.Descriptor instead.
func (*TransactionLine) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionLine) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TransactionLine) GetTransactionUUID() string {
	if x != nil {
		return x.TransactionUUID
	}
	return ""
}

func (x *TransactionLine) GetAccountUUID() string {
	if x != nil {
		return x.AccountUUID
	}
	return ""
}

func (x *TransactionLine) GetItemUUID() string {
	if x != nil {
		return x.ItemUUID
	}
	return ""
}

func (x *TransactionLine) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TransactionLine) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *TransactionLine) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TransactionLine) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionLine) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type BalanceHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path          []string               `protobuf:"bytes,2,rep,name=Path,proto3" json:"Path,omitempty"`
	AccountUUID   string                 `protobuf:"bytes,3,opt,name=AccountUUID,proto3" json:"AccountUUID,omitempty"`
	ItemUUID      string                 `protobuf:"bytes,4,opt,name=ItemUUID,proto3" json:"ItemUUID,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Quantity      float64                `protobuf:"fixed64,6,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	AvgCost       float64                `protobuf:"fixed64,7,opt,name=AvgCost,proto3" json:"AvgCost,omitempty"`
	Value         float64                `protobuf:"fixed64,8,opt,name=Value,proto3" json:"Value,omitempty"`
	DatetimeMs    int64                  `protobuf:"varint,9,opt,name=DatetimeMs,proto3" json:"DatetimeMs,omitempty"`
	Price         float64                `protobuf:"fixed64,10,opt,name=Price,proto3" json:"Price,omitempty"`
	Currency      string                 `protobuf:"bytes,11,opt,name=Currency,proto3" json:"Currency,omitempty"`
	MarketValue   float64                `protobuf:"fixed64,12,opt,name=MarketValue,proto3" json:"MarketValue,omitempty"`
	Description   string                 `protobuf:"bytes,13,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceHistory) Reset() {
	*x = BalanceHistory{}
	mi := &file_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceHistory) ProtoMessage() {}

func (x *BalanceHistory) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceHistory.ProtoReflect.Descriptor instead.
func (*BalanceHistory) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *BalanceHistory) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *BalanceHistory) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *BalanceHistory) GetAccountUUID() string {
	if x != nil {
		return x.AccountUUID
	}
	return ""
}

func (x *BalanceHistory) GetItemUUID() string {
	if x != nil {
		return x.ItemUUID
	}
	return ""
}

func (x *BalanceHistory) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *BalanceHistory) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BalanceHistory) GetAvgCost() float64 {
	if x != nil {
		return x.AvgCost
	}
	return 0
}

func (x *BalanceHistory) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *BalanceHistory) GetDatetimeMs() int64 {
	if x != nil {
		return x.DatetimeMs
	}
	return 0
}

func (x *BalanceHistory) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BalanceHistory) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BalanceHistory) GetMarketValue() float64 {
	if x != nil {
		return x.MarketValue
	}
	return 0
}

func (x *BalanceHistory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UnitConversions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUnit      string                 `protobuf:"bytes,1,opt,name=FromUnit,proto3" json:"FromUnit,omitempty"`
	ToUnit        string                 `protobuf:"bytes,2,opt,name=ToUnit,proto3" json:"ToUnit,omitempty"`
	Factor        float64                `protobuf:"fixed64,3,opt,name=Factor,proto3" json:"Factor,omitempty"`
	DatetimeMs    int64                  `protobuf:"varint,4,opt,name=DatetimeMs,proto3" json:"DatetimeMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitConversions) Reset() {
	*x = UnitConversions{}
	mi := &file_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitConversions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitConversions) ProtoMessage() {}

func (x *UnitConversions) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitConversions.ProtoReflect.Descriptor instead.
func (*UnitConversions) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *UnitConversions) GetFromUnit() string {
	if x != nil {
		return x.FromUnit
	}
	return ""
}

func (x *UnitConversions) GetToUnit() string {
	if x != nil {
		return x.ToUnit
	}
	return ""
}

func (x *UnitConversions) GetFactor() float64 {
	if x != nil {
		return x.Factor
	}
	return 0
}

func (x *UnitConversions) GetDatetimeMs() int64 {
	if x != nil {
		return x.DatetimeMs
	}
	return 0
}

type CurrencyConversions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=FromCurrency,proto3" json:"FromCurrency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=ToCurrency,proto3" json:"ToCurrency,omitempty"`
	Rate          float64                `protobuf:"fixed64,3,opt,name=Rate,proto3" json:"Rate,omitempty"`
	DatetimeMs    int64                  `protobuf:"varint,4,opt,name=DatetimeMs,proto3" json:"DatetimeMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyConversions) Reset() {
	*x = CurrencyConversions{}
	mi := &file_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyConversions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyConversions) ProtoMessage() {}

func (x *CurrencyConversions) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyConversions.ProtoReflect.Descriptor instead.
func (*CurrencyConversions) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *CurrencyConversions) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *CurrencyConversions) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *CurrencyConversions) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *CurrencyConversions) GetDatetimeMs() int64 {
	if x != nil {
		return x.DatetimeMs
	}
	return 0
}

type MarketPrices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ItemUUID      string                 `protobuf:"bytes,2,opt,name=ItemUUID,proto3" json:"ItemUUID,omitempty"`
	DatetimeMs    int64                  `protobuf:"varint,3,opt,name=DatetimeMs,proto3" json:"DatetimeMs,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=Price,proto3" json:"Price,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=Currency,proto3" json:"Currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketPrices) Reset() {
	*x = MarketPrices{}
	mi := &file_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketPrices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketPrices) ProtoMessage() {}

func (x *MarketPrices) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketPrices.ProtoReflect.Descriptor instead.
func (*MarketPrices) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *MarketPrices) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *MarketPrices) GetItemUUID() string {
	if x != nil {
		return x.ItemUUID
	}
	return ""
}

func (x *MarketPrices) GetDatetimeMs() int64 {
	if x != nil {
		return x.DatetimeMs
	}
	return 0
}

func (x *MarketPrices) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketPrices) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MarketPrices) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x12\vinventorypb\"t\n" +
	"\x04Item\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04UUID\x18\x02 \x01(\tR\x04UUID\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x04 \x01(\tR\vDescription\x12\x12\n" +
	"\x04Unit\x18\x05 \x01(\tR\x04Unit\"s\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04UUID\x18\x02 \x01(\tR\x04UUID\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"DatetimeMs\x18\x04 \x01(\x03R\n" +
	"DatetimeMs\"\xff\x01\n" +
	"\x0fTransactionLine\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12(\n" +
	"\x0fTransactionUUID\x18\x02 \x01(\tR\x0fTransactionUUID\x12 \n" +
	"\vAccountUUID\x18\x03 \x01(\tR\vAccountUUID\x12\x1a\n" +
	"\bItemUUID\x18\x04 \x01(\tR\bItemUUID\x12\x1a\n" +
	"\bQuantity\x18\x05 \x01(\x01R\bQuantity\x12\x12\n" +
	"\x04Unit\x18\x06 \x01(\tR\x04Unit\x12\x14\n" +
	"\x05Price\x18\a \x01(\x01R\x05Price\x12\x1a\n" +
	"\bCurrency\x18\b \x01(\tR\bCurrency\x12\x12\n" +
	"\x04Note\x18\t \x01(\tR\x04Note\"\xe8\x02\n" +
	"\x0eBalanceHistory\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Path\x18\x02 \x03(\tR\x04Path\x12 \n" +
	"\vAccountUUID\x18\x03 \x01(\tR\vAccountUUID\x12\x1a\n" +
	"\bItemUUID\x18\x04 \x01(\tR\bItemUUID\x12\x12\n" +
	"\x04Unit\x18\x05 \x01(\tR\x04Unit\x12\x1a\n" +
	"\bQuantity\x18\x06 \x01(\x01R\bQuantity\x12\x18\n" +
	"\aAvgCost\x18\a \x01(\x01R\aAvgCost\x12\x14\n" +
	"\x05Value\x18\b \x01(\x01R\x05Value\x12\x1e\n" +
	"\n" +
	"DatetimeMs\x18\t \x01(\x03R\n" +
	"DatetimeMs\x12\x14\n" +
	"\x05Price\x18\n" +
	" \x01(\x01R\x05Price\x12\x1a\n" +
	"\bCurrency\x18\v \x01(\tR\bCurrency\x12 \n" +
	"\vMarketValue\x18\f \x01(\x01R\vMarketValue\x12 \n" +
	"\vDescription\x18\r \x01(\tR\vDescription\"}\n" +
	"\x0fUnitConversions\x12\x1a\n" +
	"\bFromUnit\x18\x01 \x01(\tR\bFromUnit\x12\x16\n" +
	"\x06ToUnit\x18\x02 \x01(\tR\x06ToUnit\x12\x16\n" +
	"\x06Factor\x18\x03 \x01(\x01R\x06Factor\x12\x1e\n" +
	"\n" +
	"DatetimeMs\x18\x04 \x01(\x03R\n" +
	"DatetimeMs\"\x8d\x01\n" +
	"\x13CurrencyConversions\x12\"\n" +
	"\fFromCurrency\x18\x01 \x01(\tR\fFromCurrency\x12\x1e\n" +
	"\n" +
	"ToCurrency\x18\x02 \x01(\tR\n" +
	"ToCurrency\x12\x12\n" +
	"\x04Rate\x18\x03 \x01(\x01R\x04Rate\x12\x1e\n" +
	"\n" +
	"DatetimeMs\x18\x04 \x01(\x03R\n" +
	"DatetimeMs\"\xa0\x01\n" +
	"\fMarketPrices\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x1a\n" +
	"\bItemUUID\x18\x02 \x01(\tR\bItemUUID\x12\x1e\n" +
	"\n" +
	"DatetimeMs\x18\x03 \x01(\x03R\n" +
	"DatetimeMs\x12\x14\n" +
	"\x05Price\x18\x04 \x01(\x01R\x05Price\x12\x12\n" +
	"\x04Unit\x18\x05 \x01(\tR\x04Unit\x12\x1a\n" +
	"\bCurrency\x18\x06 \x01(\tR\bCurrencyB\x17Z\x15inventory/inventorypbb\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_inventory_proto_goTypes = []any{
	(*Item)(nil),                // 0: inventorypb.Item
	(*Transaction)(nil),         // 1: inventorypb.Transaction
	(*TransactionLine)(nil),     // 2: inventorypb.TransactionLine
	(*BalanceHistory)(nil),      // 3: inventorypb.BalanceHistory
	(*UnitConversions)(nil),     // 4: inventorypb.UnitConversions
	(*CurrencyConversions)(nil), // 5: inventorypb.CurrencyConversions
	(*MarketPrices)(nil),        // 6: inventorypb.MarketPrices
}
var file_inventory_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
