// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: inventory.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UUID             []byte                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ParentUUID       []byte                 `protobuf:"bytes,3,opt,name=ParentUUID,proto3" json:"ParentUUID,omitempty"`
	TransactionLines []*TransactionLine     `protobuf:"bytes,4,rep,name=TransactionLines,proto3" json:"TransactionLines,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetUUID() []byte {
	if x != nil {
		return x.UUID
	}
	return nil
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetParentUUID() []byte {
	if x != nil {
		return x.ParentUUID
	}
	return nil
}

func (x *Account) GetTransactionLines() []*TransactionLine {
	if x != nil {
		return x.TransactionLines
	}
	return nil
}

type Item struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UUID             []byte                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Unit             string                 `protobuf:"bytes,4,opt,name=Unit,proto3" json:"Unit,omitempty"`
	TransactionLines []*TransactionLine     `protobuf:"bytes,5,rep,name=TransactionLines,proto3" json:"TransactionLines,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetUUID() []byte {
	if x != nil {
		return x.UUID
	}
	return nil
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Item) GetTransactionLines() []*TransactionLine {
	if x != nil {
		return x.TransactionLines
	}
	return nil
}

type Transaction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UUID             []byte                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	DatetimeMs       int64                  `protobuf:"zigzag64,3,opt,name=DatetimeMs,proto3" json:"DatetimeMs,omitempty"`
	TransactionLines []*TransactionLine     `protobuf:"bytes,4,rep,name=TransactionLines,proto3" json:"TransactionLines,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetUUID() []byte {
	if x != nil {
		return x.UUID
	}
	return nil
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetDatetimeMs() int64 {
	if x != nil {
		return x.DatetimeMs
	}
	return 0
}

func (x *Transaction) GetTransactionLines() []*TransactionLine {
	if x != nil {
		return x.TransactionLines
	}
	return nil
}

type TransactionLine struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UUID            []byte                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	TransactionUUID []byte                 `protobuf:"bytes,2,opt,name=TransactionUUID,proto3" json:"TransactionUUID,omitempty"`
	AccountUUID     []byte                 `protobuf:"bytes,3,opt,name=AccountUUID,proto3" json:"AccountUUID,omitempty"`
	ItemUUID        []byte                 `protobuf:"bytes,4,opt,name=ItemUUID,proto3" json:"ItemUUID,omitempty"`
	Quantity        float64                `protobuf:"fixed64,5,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Unit            string                 `protobuf:"bytes,6,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Price           float64                `protobuf:"fixed64,7,opt,name=Price,proto3" json:"Price,omitempty"`
	Currency        string                 `protobuf:"bytes,8,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Note            string                 `protobuf:"bytes,9,opt,name=Note,proto3" json:"Note,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionLine) Reset() {
	*x = TransactionLine{}
	mi := &file_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionLine) ProtoMessage() {}

func (x *TransactionLine) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionLine.ProtoReflect.Descriptor instead.
func (*TransactionLine) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionLine) GetUUID() []byte {
	if x != nil {
		return x.UUID
	}
	return nil
}

func (x *TransactionLine) GetTransactionUUID() []byte {
	if x != nil {
		return x.TransactionUUID
	}
	return nil
}

func (x *TransactionLine) GetAccountUUID() []byte {
	if x != nil {
		return x.AccountUUID
	}
	return nil
}

func (x *TransactionLine) GetItemUUID() []byte {
	if x != nil {
		return x.ItemUUID
	}
	return nil
}

func (x *TransactionLine) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TransactionLine) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *TransactionLine) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TransactionLine) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionLine) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type BalanceHistoryReferences struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TransactionLineUUID []byte                 `protobuf:"bytes,1,opt,name=TransactionLineUUID,proto3" json:"TransactionLineUUID,omitempty"`
	TransactionUUID     []byte                 `protobuf:"bytes,2,opt,name=TransactionUUID,proto3" json:"TransactionUUID,omitempty"`
	AccountUUID         []byte                 `protobuf:"bytes,3,opt,name=AccountUUID,proto3" json:"AccountUUID,omitempty"`
	ItemUUID            []byte                 `protobuf:"bytes,4,opt,name=ItemUUID,proto3" json:"ItemUUID,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BalanceHistoryReferences) Reset() {
	*x = BalanceHistoryReferences{}
	mi := &file_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceHistoryReferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceHistoryReferences) ProtoMessage() {}

func (x *BalanceHistoryReferences) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceHistoryReferences.ProtoReflect.Descriptor instead.
func (*BalanceHistoryReferences) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *BalanceHistoryReferences) GetTransactionLineUUID() []byte {
	if x != nil {
		return x.TransactionLineUUID
	}
	return nil
}

func (x *BalanceHistoryReferences) GetTransactionUUID() []byte {
	if x != nil {
		return x.TransactionUUID
	}
	return nil
}

func (x *BalanceHistoryReferences) GetAccountUUID() []byte {
	if x != nil {
		return x.AccountUUID
	}
	return nil
}

func (x *BalanceHistoryReferences) GetItemUUID() []byte {
	if x != nil {
		return x.ItemUUID
	}
	return nil
}

type BalanceHistory struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	UUID             []byte                    `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Path             []string                  `protobuf:"bytes,2,rep,name=Path,proto3" json:"Path,omitempty"`
	References       *BalanceHistoryReferences `protobuf:"bytes,3,opt,name=references,proto3" json:"references,omitempty"`
	Unit             []byte                    `protobuf:"bytes,4,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Quantity         float64                   `protobuf:"fixed64,5,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	AvgCost          float64                   `protobuf:"fixed64,6,opt,name=AvgCost,proto3" json:"AvgCost,omitempty"`
	Value            float64                   `protobuf:"fixed64,7,opt,name=Value,proto3" json:"Value,omitempty"`
	DatetimeMs       int64                     `protobuf:"zigzag64,8,opt,name=DatetimeMs,proto3" json:"DatetimeMs,omitempty"`
	TransactionPrice float64                   `protobuf:"fixed64,9,opt,name=TransactionPrice,proto3" json:"TransactionPrice,omitempty"`
	MarketPrice      float64                   `protobuf:"fixed64,10,opt,name=MarketPrice,proto3" json:"MarketPrice,omitempty"`
	Currency         string                    `protobuf:"bytes,11,opt,name=Currency,proto3" json:"Currency,omitempty"`
	MarketValue      float64                   `protobuf:"fixed64,12,opt,name=MarketValue,proto3" json:"MarketValue,omitempty"`
	Description      string                    `protobuf:"bytes,13,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BalanceHistory) Reset() {
	*x = BalanceHistory{}
	mi := &file_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceHistory) ProtoMessage() {}

func (x *BalanceHistory) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceHistory.ProtoReflect.Descriptor instead.
func (*BalanceHistory) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *BalanceHistory) GetUUID() []byte {
	if x != nil {
		return x.UUID
	}
	return nil
}

func (x *BalanceHistory) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *BalanceHistory) GetReferences() *BalanceHistoryReferences {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *BalanceHistory) GetUnit() []byte {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *BalanceHistory) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BalanceHistory) GetAvgCost() float64 {
	if x != nil {
		return x.AvgCost
	}
	return 0
}

func (x *BalanceHistory) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *BalanceHistory) GetDatetimeMs() int64 {
	if x != nil {
		return x.DatetimeMs
	}
	return 0
}

func (x *BalanceHistory) GetTransactionPrice() float64 {
	if x != nil {
		return x.TransactionPrice
	}
	return 0
}

func (x *BalanceHistory) GetMarketPrice() float64 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *BalanceHistory) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BalanceHistory) GetMarketValue() float64 {
	if x != nil {
		return x.MarketValue
	}
	return 0
}

func (x *BalanceHistory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UnitConversions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUnit      string                 `protobuf:"bytes,1,opt,name=FromUnit,proto3" json:"FromUnit,omitempty"`
	ToUnit        string                 `protobuf:"bytes,2,opt,name=ToUnit,proto3" json:"ToUnit,omitempty"`
	Factor        float64                `protobuf:"fixed64,3,opt,name=Factor,proto3" json:"Factor,omitempty"`
	DatetimeMs    int64                  `protobuf:"zigzag64,4,opt,name=DatetimeMs,proto3" json:"DatetimeMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitConversions) Reset() {
	*x = UnitConversions{}
	mi := &file_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitConversions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitConversions) ProtoMessage() {}

func (x *UnitConversions) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitConversions.ProtoReflect.Descriptor instead.
func (*UnitConversions) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *UnitConversions) GetFromUnit() string {
	if x != nil {
		return x.FromUnit
	}
	return ""
}

func (x *UnitConversions) GetToUnit() string {
	if x != nil {
		return x.ToUnit
	}
	return ""
}

func (x *UnitConversions) GetFactor() float64 {
	if x != nil {
		return x.Factor
	}
	return 0
}

func (x *UnitConversions) GetDatetimeMs() int64 {
	if x != nil {
		return x.DatetimeMs
	}
	return 0
}

type CurrencyConversions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=FromCurrency,proto3" json:"FromCurrency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=ToCurrency,proto3" json:"ToCurrency,omitempty"`
	Rate          float64                `protobuf:"fixed64,3,opt,name=Rate,proto3" json:"Rate,omitempty"`
	DatetimeMs    int64                  `protobuf:"zigzag64,4,opt,name=DatetimeMs,proto3" json:"DatetimeMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyConversions) Reset() {
	*x = CurrencyConversions{}
	mi := &file_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyConversions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyConversions) ProtoMessage() {}

func (x *CurrencyConversions) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyConversions.ProtoReflect.Descriptor instead.
func (*CurrencyConversions) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *CurrencyConversions) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *CurrencyConversions) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *CurrencyConversions) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *CurrencyConversions) GetDatetimeMs() int64 {
	if x != nil {
		return x.DatetimeMs
	}
	return 0
}

type MarketPrices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemUUID      []byte                 `protobuf:"bytes,1,opt,name=ItemUUID,proto3" json:"ItemUUID,omitempty"`
	DatetimeMs    int64                  `protobuf:"zigzag64,2,opt,name=DatetimeMs,proto3" json:"DatetimeMs,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=Price,proto3" json:"Price,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=Currency,proto3" json:"Currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketPrices) Reset() {
	*x = MarketPrices{}
	mi := &file_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketPrices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketPrices) ProtoMessage() {}

func (x *MarketPrices) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketPrices.ProtoReflect.Descriptor instead.
func (*MarketPrices) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *MarketPrices) GetItemUUID() []byte {
	if x != nil {
		return x.ItemUUID
	}
	return nil
}

func (x *MarketPrices) GetDatetimeMs() int64 {
	if x != nil {
		return x.DatetimeMs
	}
	return 0
}

func (x *MarketPrices) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketPrices) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MarketPrices) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          []byte                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Type          int32                  `protobuf:"zigzag32,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Meta          map[string][]byte      `protobuf:"bytes,3,rep,name=Meta,proto3" json:"Meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          map[string][]byte      `protobuf:"bytes,4,rep,name=Body,proto3" json:"Body,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *Packet) GetUUID() []byte {
	if x != nil {
		return x.UUID
	}
	return nil
}

func (x *Packet) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Packet) GetMeta() map[string][]byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Packet) GetBody() map[string][]byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type MapOfBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       map[string][]byte      `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapOfBytes) Reset() {
	*x = MapOfBytes{}
	mi := &file_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapOfBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapOfBytes) ProtoMessage() {}

func (x *MapOfBytes) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapOfBytes.ProtoReflect.Descriptor instead.
func (*MapOfBytes) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *MapOfBytes) GetContent() map[string][]byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x12\vinventorypb\"\x9b\x01\n" +
	"\aAccount\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\fR\x04UUID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"ParentUUID\x18\x03 \x01(\fR\n" +
	"ParentUUID\x12H\n" +
	"\x10TransactionLines\x18\x04 \x03(\v2\x1c.inventorypb.TransactionLineR\x10TransactionLines\"\xae\x01\n" +
	"\x04Item\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\fR\x04UUID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x12\n" +
	"\x04Unit\x18\x04 \x01(\tR\x04Unit\x12H\n" +
	"\x10TransactionLines\x18\x05 \x03(\v2\x1c.inventorypb.TransactionLineR\x10TransactionLines\"\xad\x01\n" +
	"\vTransaction\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\fR\x04UUID\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"DatetimeMs\x18\x03 \x01(\x12R\n" +
	"DatetimeMs\x12H\n" +
	"\x10TransactionLines\x18\x04 \x03(\v2\x1c.inventorypb.TransactionLineR\x10TransactionLines\"\x83\x02\n" +
	"\x0fTransactionLine\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\fR\x04UUID\x12(\n" +
	"\x0fTransactionUUID\x18\x02 \x01(\fR\x0fTransactionUUID\x12 \n" +
	"\vAccountUUID\x18\x03 \x01(\fR\vAccountUUID\x12\x1a\n" +
	"\bItemUUID\x18\x04 \x01(\fR\bItemUUID\x12\x1a\n" +
	"\bQuantity\x18\x05 \x01(\x01R\bQuantity\x12\x12\n" +
	"\x04Unit\x18\x06 \x01(\tR\x04Unit\x12\x14\n" +
	"\x05Price\x18\a \x01(\x01R\x05Price\x12\x1a\n" +
	"\bCurrency\x18\b \x01(\tR\bCurrency\x12\x12\n" +
	"\x04Note\x18\t \x01(\tR\x04Note\"\xb4\x01\n" +
	"\x18BalanceHistoryReferences\x120\n" +
	"\x13TransactionLineUUID\x18\x01 \x01(\fR\x13TransactionLineUUID\x12(\n" +
	"\x0fTransactionUUID\x18\x02 \x01(\fR\x0fTransactionUUID\x12 \n" +
	"\vAccountUUID\x18\x03 \x01(\fR\vAccountUUID\x12\x1a\n" +
	"\bItemUUID\x18\x04 \x01(\fR\bItemUUID\"\xad\x03\n" +
	"\x0eBalanceHistory\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\fR\x04UUID\x12\x12\n" +
	"\x04Path\x18\x02 \x03(\tR\x04Path\x12E\n" +
	"\n" +
	"references\x18\x03 \x01(\v2%.inventorypb.BalanceHistoryReferencesR\n" +
	"references\x12\x12\n" +
	"\x04Unit\x18\x04 \x01(\fR\x04Unit\x12\x1a\n" +
	"\bQuantity\x18\x05 \x01(\x01R\bQuantity\x12\x18\n" +
	"\aAvgCost\x18\x06 \x01(\x01R\aAvgCost\x12\x14\n" +
	"\x05Value\x18\a \x01(\x01R\x05Value\x12\x1e\n" +
	"\n" +
	"DatetimeMs\x18\b \x01(\x12R\n" +
	"DatetimeMs\x12*\n" +
	"\x10TransactionPrice\x18\t \x01(\x01R\x10TransactionPrice\x12 \n" +
	"\vMarketPrice\x18\n" +
	" \x01(\x01R\vMarketPrice\x12\x1a\n" +
	"\bCurrency\x18\v \x01(\tR\bCurrency\x12 \n" +
	"\vMarketValue\x18\f \x01(\x01R\vMarketValue\x12 \n" +
	"\vDescription\x18\r \x01(\tR\vDescription\"}\n" +
	"\x0fUnitConversions\x12\x1a\n" +
	"\bFromUnit\x18\x01 \x01(\tR\bFromUnit\x12\x16\n" +
	"\x06ToUnit\x18\x02 \x01(\tR\x06ToUnit\x12\x16\n" +
	"\x06Factor\x18\x03 \x01(\x01R\x06Factor\x12\x1e\n" +
	"\n" +
	"DatetimeMs\x18\x04 \x01(\x12R\n" +
	"DatetimeMs\"\x8d\x01\n" +
	"\x13CurrencyConversions\x12\"\n" +
	"\fFromCurrency\x18\x01 \x01(\tR\fFromCurrency\x12\x1e\n" +
	"\n" +
	"ToCurrency\x18\x02 \x01(\tR\n" +
	"ToCurrency\x12\x12\n" +
	"\x04Rate\x18\x03 \x01(\x01R\x04Rate\x12\x1e\n" +
	"\n" +
	"DatetimeMs\x18\x04 \x01(\x12R\n" +
	"DatetimeMs\"\x90\x01\n" +
	"\fMarketPrices\x12\x1a\n" +
	"\bItemUUID\x18\x01 \x01(\fR\bItemUUID\x12\x1e\n" +
	"\n" +
	"DatetimeMs\x18\x02 \x01(\x12R\n" +
	"DatetimeMs\x12\x14\n" +
	"\x05Price\x18\x03 \x01(\x01R\x05Price\x12\x12\n" +
	"\x04Unit\x18\x04 \x01(\tR\x04Unit\x12\x1a\n" +
	"\bCurrency\x18\x05 \x01(\tR\bCurrency\"\x88\x02\n" +
	"\x06Packet\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\fR\x04UUID\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\x11R\x04Type\x121\n" +
	"\x04Meta\x18\x03 \x03(\v2\x1d.inventorypb.Packet.MetaEntryR\x04Meta\x121\n" +
	"\x04Body\x18\x04 \x03(\v2\x1d.inventorypb.Packet.BodyEntryR\x04Body\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a7\n" +
	"\tBodyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x88\x01\n" +
	"\n" +
	"MapOfBytes\x12>\n" +
	"\acontent\x18\x01 \x03(\v2$.inventorypb.MapOfBytes.ContentEntryR\acontent\x1a:\n" +
	"\fContentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B\x17Z\x15inventory/inventorypbb\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_inventory_proto_goTypes = []any{
	(*Account)(nil),                  // 0: inventorypb.Account
	(*Item)(nil),                     // 1: inventorypb.Item
	(*Transaction)(nil),              // 2: inventorypb.Transaction
	(*TransactionLine)(nil),          // 3: inventorypb.TransactionLine
	(*BalanceHistoryReferences)(nil), // 4: inventorypb.BalanceHistoryReferences
	(*BalanceHistory)(nil),           // 5: inventorypb.BalanceHistory
	(*UnitConversions)(nil),          // 6: inventorypb.UnitConversions
	(*CurrencyConversions)(nil),      // 7: inventorypb.CurrencyConversions
	(*MarketPrices)(nil),             // 8: inventorypb.MarketPrices
	(*Packet)(nil),                   // 9: inventorypb.Packet
	(*MapOfBytes)(nil),               // 10: inventorypb.MapOfBytes
	nil,                              // 11: inventorypb.Packet.MetaEntry
	nil,                              // 12: inventorypb.Packet.BodyEntry
	nil,                              // 13: inventorypb.MapOfBytes.ContentEntry
}
var file_inventory_proto_depIdxs = []int32{
	3,  // 0: inventorypb.Account.TransactionLines:type_name -> inventorypb.TransactionLine
	3,  // 1: inventorypb.Item.TransactionLines:type_name -> inventorypb.TransactionLine
	3,  // 2: inventorypb.Transaction.TransactionLines:type_name -> inventorypb.TransactionLine
	4,  // 3: inventorypb.BalanceHistory.references:type_name -> inventorypb.BalanceHistoryReferences
	11, // 4: inventorypb.Packet.Meta:type_name -> inventorypb.Packet.MetaEntry
	12, // 5: inventorypb.Packet.Body:type_name -> inventorypb.Packet.BodyEntry
	13, // 6: inventorypb.MapOfBytes.content:type_name -> inventorypb.MapOfBytes.ContentEntry
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
